# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, ttk
from tkcalendar import DateEntry
import tkinter as tk
from DbConnectionClass import DatabaseConnection
class NewProducts(tk.Frame):

    def __init__(self, parent, controller):
        tk.Frame.__init__(self, parent)
        self.controller = controller

        OUTPUT_PATH = Path(__file__).parent
        ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame131415")

        def relative_to_assets(path: str) -> Path:
            return ASSETS_PATH / Path(path)

        controller.geometry("360x800")
        controller.configure(bg = "#373361")

        canvas = Canvas(
            self,
            bg = "#373361",
            height = 800,
            width = 360,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            19.0,
            80.0,
            342.0,
            631.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            38.0,
            185.0, #y0 and y1 = 65 (the diff)
            323.0,
            260.0, #y0 + 65
            fill="#B485FD",
            outline="")
        name_prompt = canvas.create_text(
            43.0,
            210.0, # y0 + 25
            anchor="nw",
            text="Product: ",
            fill="#FFFFFF",
            font=("JacquesFrancois Regular", 20 * -1)
        )
        self.product_name = Entry(canvas)
        canvas.create_window(
            200.0,
            220.0, # y0 + 35
            width=170,
            window=self.product_name)
        canvas.create_rectangle(
            63.0,
            232.0, # y0 +47
            295.0,
            233.0, # y0 +48
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            38.0,
            270.0, #y0 and y1 = 65 (the diff)
            323.0,
            335.0, #y0 + 65
            fill="#B485FD",
            outline="")
        type_prompt = canvas.create_text(
            55.0,
            295.0, # y0 + 25
            anchor="nw",
            text="Type: ",
            fill="#FFFFFF",
            font=("JacquesFrancois Regular", 20 * -1)
        )
        self.productType = Entry(canvas)
        canvas.create_window(
            200.0,
            305.0, # y0 + 35
            width=170,
            window=self.productType)
        canvas.create_rectangle(
            63.0,
            317.0, # y0 +47
            295.0,
            318.0, # y0 +48
            fill="#000000",
            outline="")
        canvas.create_rectangle(
            320.0,#top x coordinate
            180.0,#top y coordinate
            38.0,#bottom x coordinate
            95.0,#bottom y coordinate
            fill="#B485FD",
            outline="")

        supplier_name = canvas.create_text(
            74.0,
            105.0,
            anchor="nw",
            text="Enter Supplier Name:",
            fill="#FFFFFF",
            font=("JacquesFrancois Regular", 20 * -1)
        )

        self.options = ""
        self.labels = ""
        def combobox_field_change(*args):
            print("combo box update to ", self.selected_label.get())
            self.item_no_id = self.selected_label.get().split(" ", 1)
            canvas.itemconfigure(supplier_name, text=self.item_no_id[0])

        self.selected_label = tk.StringVar()
        self.combobox = ttk.Combobox(canvas, values=self.labels, textvariable=self.selected_label)
        self.combobox.pack()
        self.combobox.place(x=100, y=140)
        self.selected_label.trace('w', combobox_field_change)

        canvas.create_rectangle(
            38.0,
            345.0, #y0 and y1 = 65 (the diff)
            323.0,
            405.0, #y0 + 65
            fill="#B485FD",
            outline="")
        unit_prompt = canvas.create_text(
            55.0,
            360.0, # y0 + 25
            anchor="nw",
            text="Unit: ",
            fill="#FFFFFF",
            font=("JacquesFrancois Regular", 20 * -1)
        )
        self.unit = Entry(canvas)
        canvas.create_window(
            200.0,
            370.0, # y0 + 35
            width=170,
            window=self.unit)
        canvas.create_rectangle(
            63.0,
            382.0, # y0 +47
            295.0,
            383.0, # y0 +48
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            38.0,
            420.0, #y0 and y1 = 65 (the diff)
            323.0,
            485.0, #y0 + 65
            fill="#B485FD",
            outline="")
        phone_prompt = canvas.create_text(
            55.0,
            445.0, # y0 + 25
            anchor="nw",
            text="Unit Type: ",
            fill="#FFFFFF",
            font=("JacquesFrancois Regular", 20 * -1)
        )
        self.UnitType = Entry(canvas)
        canvas.create_window(
            200.0,
            455.0, # y0 + 35
            width=170,
            window=self.UnitType)
        canvas.create_rectangle(
            63.0,
            467.0, # y0 +47
            295.0,
            468.0, # y0 +48
            fill="#000000",
            outline="")

        self.options = ""
        self.labels = ""

        canvas.create_text(
            15.0,
            9.0,
            anchor="nw",
            text="New Product ",
            fill="#FFFFFF",
            font=("JacquesFrancois Regular", 24 * -1)
        )

        self.button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        button_1 = Button(
            canvas,
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: [print("insert new supplier button clicked"), insert_new_product()],
            relief="flat"
        )
        button_1.place(
            x=64.0,
            y=500.0,
            width=231.0,
            height=59.0
        )

        from gui11 import HeadChefAdvancedMenu
        self.button_image_2 = PhotoImage(
            file=relative_to_assets("button_2.png"))
        button_2 = Button(
            canvas,
            image=self.button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: [controller.show_current_frame(HeadChefAdvancedMenu), print("back button (add item) clicked")],
            relief="flat"
        )
        button_2.place(
            x=125.0,
            y=574.0,
            width=111.0,
            height=45.0
        )

        controller.resizable(False, False)

        def insert_new_product():
            #product name
            productName = str(self.product_name.get() ) #done

            #product type
            productType = str( self.productType.get() ) #done

            #supplier name
            supplierName = str( self.selected_label.get() )

            #unit
            unit = str( self.unit.get() )

            # unit type
            unitType = str( self.UnitType.get() )

            #insert into db
            db_conn = DatabaseConnection()
            db_conn.connect()

            result = db_conn.query_no_data("SELECT MAX(productId) FROM `ba4wmpjwd2fynuzr9vvq`.`product`")
            print(f"result of max productid query: {result[0][0]}")
            new_product_id = result[0][0] + 1 if result[0][0] is not None else 1


            query = """INSERT INTO `ba4wmpjwd2fynuzr9vvq`.`product`(`productId`,`productName`,`productType`,`supplierName`,`unit`,`unit_type`)VALUES (%s, %s, %s, %s, %s, %s)"""
            query_data = (new_product_id, productName, productType, supplierName, unit, unitType)
            db_conn.execute(query, query_data)
            db_conn.close()

    def update_fridge_items(self):
        db_conn = DatabaseConnection()
        db_conn.connect()
        query = ("SELECT * FROM supplier")
        self.supplier_details = db_conn.query_no_data(query)
        db_conn.close()

        self.options = [row[0] for row in self.supplier_details]
        self.labels = [row for row in self.supplier_details]
        print(f"labels to be put in combobox: {self.labels}")
        self.combobox['values'] =(self.options)