
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, ttk
from tkcalendar import DateEntry
import tkinter as tk
from DbConnectionClass import DatabaseConnection
class NewSupplier(tk.Frame):

    def __init__(self, parent, controller):
        tk.Frame.__init__(self, parent)
        self.controller = controller

        OUTPUT_PATH = Path(__file__).parent
        ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame131415")

        def relative_to_assets(path: str) -> Path:
            return ASSETS_PATH / Path(path)

        controller.geometry("360x800")
        controller.configure(bg = "#373361")

        canvas = Canvas(
            self,
            bg = "#373361",
            height = 800,
            width = 360,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            19.0,
            166.0,
            342.0,
            631.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            38.0,
            185.0, #y0 and y1 = 65 (the diff)
            323.0,
            250.0, #y0 + 65
            fill="#B485FD",
            outline="")
        name_prompt = canvas.create_text(
            55.0,
            210.0, # y0 + 25
            anchor="nw",
            text="Name: ",
            fill="#FFFFFF",
            font=("JacquesFrancois Regular", 20 * -1)
        )
        self.supplier_name = Entry(canvas)
        canvas.create_window(
            200.0,
            220.0, # y0 + 35
            width=170,
            window=self.supplier_name)
        canvas.create_rectangle(
            63.0,
            232.0, # y0 +47
            295.0,
            233.0, # y0 +48
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            38.0,
            270.0, #y0 and y1 = 65 (the diff)
            323.0,
            335.0, #y0 + 65
            fill="#B485FD",
            outline="")
        address_prompt = canvas.create_text(
            38.0,
            295.0, # y0 + 25
            anchor="nw",
            text="Address: ",
            fill="#FFFFFF",
            font=("JacquesFrancois Regular", 20 * -1)
        )
        self.supplier_address = Entry(canvas)
        canvas.create_window(
            200.0,
            305.0, # y0 + 35
            width=170,
            window=self.supplier_address)
        canvas.create_rectangle(
            63.0,
            317.0, # y0 +47
            295.0,
            318.0, # y0 +48
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            38.0,
            355.0, #y0 and y1 = 65 (the diff)
            323.0,
            400.0, #y0 + 65
            fill="#B485FD",
            outline="")
        email_prompt = canvas.create_text(
            55.0,
            360.0, # y0 + 25
            anchor="nw",
            text="Email: ",
            fill="#FFFFFF",
            font=("JacquesFrancois Regular", 20 * -1)
        )
        self.supplier_email = Entry(canvas)
        canvas.create_window(
            200.0,
            370.0, # y0 + 35
            width=170,
            window=self.supplier_email)
        canvas.create_rectangle(
            63.0,
            382.0, # y0 +47
            295.0,
            383.0, # y0 +48
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            38.0,
            420.0, #y0 and y1 = 65 (the diff)
            323.0,
            485.0, #y0 + 65
            fill="#B485FD",
            outline="")
        phone_prompt = canvas.create_text(
            55.0,
            445.0, # y0 + 25
            anchor="nw",
            text="Phone #: ",
            fill="#FFFFFF",
            font=("JacquesFrancois Regular", 20 * -1)
        )
        self.supplier_phone = Entry(canvas)
        canvas.create_window(
            200.0,
            455.0, # y0 + 35
            width=170,
            window=self.supplier_phone)
        canvas.create_rectangle(
            63.0,
            467.0, # y0 +47
            295.0,
            468.0, # y0 +48
            fill="#000000",
            outline="")

        self.options = ""
        self.labels = ""

        canvas.create_text(
            15.0,
            9.0,
            anchor="nw",
            text="New Supplier ",
            fill="#FFFFFF",
            font=("JacquesFrancois Regular", 24 * -1)
        )

        self.button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        button_1 = Button(
            canvas,
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: [print("insert new supplier button clicked"), insert_new_supplier()],
            relief="flat"
        )
        button_1.place(
            x=64.0,
            y=500.0,
            width=231.0,
            height=59.0
        )

        from gui11 import HeadChefAdvancedMenu
        self.button_image_2 = PhotoImage(
            file=relative_to_assets("button_2.png"))
        button_2 = Button(
            canvas,
            image=self.button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: [controller.show_current_frame(HeadChefAdvancedMenu), print("back button (add item) clicked")],
            relief="flat"
        )
        button_2.place(
            x=125.0,
            y=574.0,
            width=111.0,
            height=45.0
        )

        controller.resizable(False, False)

        def insert_new_supplier():
            #supplier name
            name = self.supplier_name.get()
            #supplier address
            address = self.supplier_address.get()
            #supplier email
            email = self.supplier_email.get()
            #supplier phonenr
            phone = self.supplier_phone.get()

            #insert into db
            db_conn = DatabaseConnection()
            db_conn.connect()
            query = """INSERT INTO supplier (supplierName, supplierAddress, supplierEmail, supplierPhoneNr) VALUES (%s, %s, %s, %s)"""
            query_data = (name, address, email, phone)
            users_exists_check = db_conn.execute(query, query_data)
            db_conn.close()
