
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, ttk
import tkinter as tk
from DbConnectionClass import DatabaseConnection

class RemoveItem(tk.Frame):

    def __init__(self, parent, controller):
        tk.Frame.__init__(self, parent)
        self.controller = controller

        OUTPUT_PATH = Path(__file__).parent
        ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame1")


        def relative_to_assets(path: str) -> Path:
            return ASSETS_PATH / Path(path)

        controller.geometry("360x800")
        controller.configure(bg = "#373361")


        canvas = Canvas(
            self,
            bg = "#373361",
            height = 800,
            width = 360,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            19.0,
            166.0,
            342.0,
            536.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            38.0,
            245.0,
            323.0,
            332.0,
            fill="#B485FD",
            outline="")

        item_code = canvas.create_text(
            99.0,
            272.0,
            anchor="nw",
            text="Select Item",
            fill="#FFFFFF",
            font=("JacquesFrancois Regular", 20 * -1)
        )

        canvas.create_text(
            15.0,
            9.0,
            anchor="nw",
            text="Update item ",
            fill="#FFFFFF",
            font=("JacquesFrancois Regular", 24 * -1)
        )

        self.options = ""
        self.labels = ""

        def combobox_field_change(*args):
            print("combo box update to ", self.selected_label.get())
            self.item_no_id = self.selected_label.get().split(" ", 1)
            self.fride_item_id = self.selected_label.get().split(" ", 8)[8]
            self.product_name = self.selected_label.get().split(" ", 8)[1]
            self.product_valid_date = self.selected_label.get().split(" ", 8)[4]
            self.product_quantity = self.selected_label.get().split(" ", 8)[7]

            canvas.itemconfigure(item_code, text=(self.product_quantity + " " + self.product_name + " " + self.product_valid_date ) )

        self.selected_label = tk.StringVar()
        self.combobox = ttk.Combobox(canvas, values=self.labels, textvariable=self.selected_label, width= 40)

        self.combobox.pack()
        self.combobox.place(x=55,y=300)

        self.selected_label.trace('w', combobox_field_change)

        canvas.create_rectangle(
            63.0,
            308.0,
            295.0,
            309.0,
            fill="#000000",
            outline="")

        self.button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        button_1 = Button(
            canvas,
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: [print("button_1 (remove_item) clicked"), update_fridge_value_button_event()], #update fridge quantity for item
            relief="flat"
        )
        button_1.place(
            x=64.0,
            y=419.0,
            width=231.0,
            height=59.0
        )

        canvas.create_rectangle(
            136.0,
            355.0,
            214.0,
            400.0,
            fill="#F24B4B",
            outline="")

        from gui8 import MainMenu
        from gui10 import HeadChefNormalMenu

        self.button_image_2 = PhotoImage(
            file=relative_to_assets("button_2.png")) #back button
        button_2 = Button(
            canvas,
            image=self.button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: controller.show_current_frame(HeadChefNormalMenu) if controller.account_type=="HeadChef" else controller.show_current_frame(MainMenu),
            relief="flat"
        )
        button_2.place(
            x=125.0,
            y=574.0,
            width=111.0,
            height=45.0
        )

        canvas.create_text(
            152.0,
            362.0,
            anchor="nw",
            text="Q",
            fill="#FFFFFF",
            font=("JacquesFrancois Regular", 20 * -1)
        )

        self.unit_quantity = Entry(canvas)
        canvas.create_window(
            192.0,
            362.0,
            width=50,
            window=self.unit_quantity)

        controller.resizable(False, False)

        def update_fridge_value_button_event():
            #get item id
            fridge_id = int(self.fride_item_id)
            #get unit quantity
            unit_quantity = self.unit_quantity.get()
            #send sql insert to fridge table

            db_conn = DatabaseConnection()
            db_conn.connect()
            query = """UPDATE `ba4wmpjwd2fynuzr9vvq`.`fridge` SET `quantity` = %s WHERE `fridge_id`= %s"""
            query_data = (unit_quantity, fridge_id)
            users_exists_check = db_conn.execute(query, query_data)

            execute = """SET SQL_SAFE_UPDATES = 0"""
            db_conn.execute_no_data(execute)
            execute =  """DELETE FROM `ba4wmpjwd2fynuzr9vvq`.`fridge` WHERE `quantity`=0"""
            db_conn.execute_no_data(execute)
            execute = """SET SQL_SAFE_UPDATES=1"""
            db_conn.execute_no_data(execute)

            db_conn.close()

            self.update_fridge_items()

    def update_fridge_items(self):
        db_conn = DatabaseConnection()
        db_conn.connect()
        query = ("SELECT * FROM delete_prod")
        query_data = ""
        self.product_details = db_conn.query(query, query_data)
        db_conn.close()

        self.options = [row[0] for row in self.product_details]
        self.labels = [row for row in self.product_details]
        self.product_names = [row[1] for row in self.product_details]
        self.validation_dates = [row[4] for row in self.product_details]
        print(f"labels to be put in combobox: {self.labels}")
        self.combobox['values'] = (self.labels)
